load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mppg",
    calculators = [
    "//mediapipe/graphs/portrait_segmentation:mobile_calculators"]
)